### ISSUE TITLE
KeyError: 'text'

### ISSUE THREAD

**Issue by scvready123** [simplescaling/s1#39]
Hello, I encountered an error when running the sft.sh:

[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/anaconda3/envs/s1/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 513, in tokenize
[rank0]:     element[dataset_text_field] if formatting_func is None else formatting_func(element),
[rank0]:     ~~~~~~~^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/anaconda3/envs/s1/lib/python3.11/site-packages/datasets/formatting/formatting.py", line 277, in __getitem__
[rank0]:     value = self.data[key]
[rank0]:             ~~~~~~~~~^^^^^
[rank0]: KeyError: 'text'

It seems that there is no "text" field in your simplescaling/s1K dataset. I wonder how to solve it, thanks!

**Comment by Muennighoff** [comment]
Sorry it should be `simplescaling/s1K_tokenized` which has that column; I think it is already fixed on main?

**Comment by danazhang** [comment]
I also have this question,it seems the problem is not fixed yet

**Comment by Muennighoff** [comment]
What script are you running? I recommend using https://hf.co/datasets/simplescaling/s1K-1.1_tokenized

**Comment by HwangYej1** [comment]
i also have this question, have you fixed it ?
